#!/bin/bash

# RooInstaller Global Installation
# This script installs RooInstaller as a global command
# so it can be used from anywhere in your system
# 
# Author: Albert Arno
# License: Apache 2.0

# Global installer for RooInstaller
# This script installs RooInstaller globally so it can be used from anywhere

# Find the script directory (even if run through symlink)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}RooInstaller Global Setup${NC}"

# Make the scripts executable
chmod +x "$SCRIPT_DIR/install.sh"
chmod +x "$SCRIPT_DIR/rooinstaller.js"

# Determine the best location for the global command
# Try /usr/local/bin first, then fall back to ~/bin if needed
# Create a wrapper script that will call the install.sh with proper path

# Get the absolute path of the script directory
ABSOLUTE_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cat > "$SCRIPT_DIR/rooinstall" << EOL
#!/bin/bash

# Generated by global-install.sh
# RooInstaller global command wrapper

# Run the installer with any arguments passed
"\$(dirname \$(readlink -f \$0))/install.sh" "\$@"
EOL

# Make the wrapper executable
chmod +x "$SCRIPT_DIR/rooinstall"

# Try to install to /usr/local/bin first
if [ -d "/usr/local/bin" ]; then
  DESTINATION="/usr/local/bin/rooinstall"
  
  # Check if we have write permissions
  if [ -w "/usr/local/bin" ]; then
    # Install without sudo
    if [ -e "$DESTINATION" ]; then
      rm "$DESTINATION"
    fi
    
    cp "$SCRIPT_DIR/rooinstall" "$DESTINATION"
    echo -e "${GREEN}Successfully installed RooInstaller globally in /usr/local/bin!${NC}"
    echo -e "You can now run ${CYAN}rooinstall${NC} from anywhere to install RooFlow in your project."
  else
    # Try with sudo
    echo -e "${YELLOW}No write permissions for /usr/local/bin. Trying with sudo...${NC}"
    echo "This will prompt for your password."
    
    sudo cp "$SCRIPT_DIR/rooinstall" "$DESTINATION"
    
    if [ $? -eq 0 ]; then
      echo -e "${GREEN}Successfully installed RooInstaller globally in /usr/local/bin!${NC}"
      echo -e "You can now run ${CYAN}rooinstall${NC} from anywhere to install RooFlow in your project."
    else
      # Fall back to user's bin directory
      install_to_user_bin
    fi
  fi
else
  # Fall back to user's bin directory
  install_to_user_bin
fi

# Function to install to user's bin directory
install_to_user_bin() {
  USER_BIN="$HOME/bin"
  USER_DESTINATION="$USER_BIN/rooinstall"
  
  # Create ~/bin if it doesn't exist
  if [ ! -d "$USER_BIN" ]; then
    mkdir -p "$USER_BIN"
    echo -e "${YELLOW}Created directory $USER_BIN${NC}"
    
    # Add to PATH if needed
    if [[ ":$PATH:" != *":$USER_BIN:"* ]]; then
      echo -e "${YELLOW}Adding $USER_BIN to your PATH in ~/.bashrc${NC}"
      echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"
      echo -e "${YELLOW}Note: You'll need to restart your terminal or run 'source ~/.bashrc'${NC}"
    fi
  fi
  
  # Install to user bin
  cp "$SCRIPT_DIR/rooinstall" "$USER_DESTINATION"
  chmod +x "$USER_DESTINATION"
  
  echo -e "${GREEN}Successfully installed RooInstaller in $USER_BIN!${NC}"
  echo -e "You can now run ${CYAN}rooinstall${NC} from anywhere to install RooFlow in your project."
  
  if [[ ":$PATH:" != *":$USER_BIN:"* ]]; then
    echo -e "${YELLOW}Important: You need to restart your terminal or run 'source ~/.bashrc' before using the command.${NC}"
  fi
}
